clinica/urls.py
from django.urls import path

from . import views

app_name = 'clinica'
urlpatterns = [
    # Urls de pacientes
    path('pacientes/', views.PacientesListView.as_view(), name='pacientes'),
    path('pacientes/pacientes-json/', views.PacientesListJson.as_view(), name='pacientes-json'),
    path('pacientes/paciente-create/', views.PacienteCreateView.as_view(), name='paciente-create'),
    path('pacientes/<int:pk>/paciente-update/', views.PacienteUpdateView.as_view(), name='paciente-update'),
    path('pacientes/<int:pk>/paciente-delete/', views.PacienteDeleteJsonView.as_view(), name='paciente-delete'),
    path('pacientes/<int:pk>/paciente-details/', views.PacienteDetallesView.as_view(), name='paciente-details'),
    path('pacientes/<int:pk>/paciente-inactivo/', views.PacienteInactivoJsonView.as_view(), name='paciente-inactivo'),

    # Urls de doctores
    path('doctores/', views.DoctoresListView.as_view(), name='doctores'),
    path('doctores/doctores-json/', views.DoctoresListJson.as_view(), name='doctores-json'),
    path('doctores/doctor-create/', views.DoctorCreateView.as_view(), name='doctor-create'),
    path('doctores/<int:pk>/menu-update/', views.DoctorUpdateView.as_view(), name='doctor-update'),
    path('doctores/<int:pk>/delete-update/', views.DoctorDeleteJsonView.as_view(), name='doctor-delete'),
    path('doctores/<int:pk>/doctore-details/', views.DoctorDetallesView.as_view(), name='doctor-details'),
    path('doctores/<int:pk>/doctore-estado/', views.DoctorEstadoJsonView.as_view(), name='doctor-estado'),
    # Urls de menus
    path('categorias/', views.CategoriasListView.as_view(), name='categorias'),
    path('categorias/categorias-json/', views.CategoriasListJson.as_view(), name='categorias-json'),
    path('categorias/categoria-create/', views.CategoriaCreateView.as_view(), name='categoria-create'),
    path('categorias/<int:pk>/categoria-update/', views.CategoriaUpdateView.as_view(), name='categoria-update'),
    path('categorias/<int:pk>/cateogria-delete/', views.CategoriaDeleteJsonView.as_view(), name='categoria-delete'),

    # Urls de citas
    path('citas/', views.CitasListView.as_view(), name='citas'),
    path('citas/citas-json/', views.CitasListJson.as_view(), name='citas-json'),
    path('citas/cita-create/', views.CitaCreateView.as_view(), name='cita-create'),
    path('citas/<int:pk>/menu-update/', views.CitaUpdateView.as_view(), name='cita-update'),
    path('citas/<int:pk>/delete-update/', views.CitaDeleteJsonView.as_view(),
         name='cita-delete'),

    # Urls de Diagnosticos
    path('diagnosticos/<int:cita_id>/diagnostico-new/', views.DiagnosticoNewView.as_view(), name='diagnostico-new'),
    path('diagnosticos/<int:pk>/diagnostico-detatils/', views.DiagnosticoDetailsView.as_view(),
         name='diagnostico-details'),

    # Urls de historial
    path('historial/', views.HistorialListView.as_view(), name='historial'),
    path('historial/historial-json/', views.HistorialListJson.as_view(), name='historial-json'),
]

nutricion_igss/urls.py
from django.contrib import admin
from django.contrib.auth.views import LoginView
from django.urls import path, include

from nutricion_igss import views
from catalogos import urls as catalogos_urls
from clinica import urls as clinica_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('login/', LoginView.as_view()),
    path('', views.index, name='index'),
    path('', include(catalogos_urls)),
    path('', include(clinica_urls)),
]

clinica/forms/formularios.py
from clinica.models import Paciente, Doctor, Cita, Categoria, Diagnostico, Medida, Peso, Fisioterapia, Quiropractica
from utils.FormMixim import FieldSetModelFormMixin, LargeFormMixin


class PacienteForm(FieldSetModelFormMixin):
    class Meta:
        model = Paciente
        fields = [
            'nombre', 'apellido', 'direccion', 'telefono', 'edad', 'dpi', 'genero'
        ]


class DoctorForm(FieldSetModelFormMixin):
    class Meta:
        model = Doctor
        fields = '__all__'


class CategoriaForm(FieldSetModelFormMixin):
    class Meta:
        model = Categoria
        fields = '__all__'


class CitaForm(FieldSetModelFormMixin):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['paciente'].queryset = Paciente.objects.filter(estado=1)
        self.fields['doctor'].queryset = Doctor.objects.filter(estado=1)

        self.fields['paciente'].widget.attrs['class'] = "select2"

    class Meta:
        model = Cita
        fields = '__all__'


class PesoForm(FieldSetModelFormMixin):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['imc'].widget.attrs['readonly'] = True
        self.fields['peso'].widget.attrs['step'] = "1"
        self.fields['peso'].widget.attrs['min'] = "0"
        self.fields['estatura'].widget.attrs['step'] = "1"
        self.fields['estatura'].widget.attrs['min'] = "0"

    class Meta:
        model = Peso
        fields = [
            'peso', 'estatura', 'imc', 'grasa', 'agua', 'masa_muscular', 'complexion_fisica', 'metabolismo_basal',
            'edad_metabolica', 'masa_osea'
        ]


class MedidaForm(FieldSetModelFormMixin):
    class Meta:
        model = Medida
        fields = ['abdomen_superior', 'cintura', 'abdomen_inferior', 'circunferencia_brazo',
                  'circunferencia_muslo']


class FisioterapiaForm(FieldSetModelFormMixin):
    class Meta:
        model = Fisioterapia
        fields = ['precio_f']


class QuiropracticaForm(FieldSetModelFormMixin):
    class Meta:
        model = Quiropractica
        fields = ['precio_q']


class DiagnosticoForm(LargeFormMixin):
    class Meta:
        model = Diagnostico
        fields = ['id', 'fecha', 'diagnostico', 'reseta', 'lunes', 'martes', 'miercoles', 'jueves', 'viernes', 'sabado',
                  'domingo']

clinica/views.py
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from django.db import transaction
from django.db.models import QuerySet
from django.forms import formset_factory

from django.http import JsonResponse, HttpResponseRedirect

from django.urls import reverse_lazy
from django.views.generic import TemplateView, CreateView, UpdateView, DetailView
from django_datatables_view.base_datatable_view import BaseDatatableView

from clinica.forms import PacienteForm, DoctorForm, CitaForm, Cita, CategoriaForm, PesoForm, \
    MedidaForm, Diagnostico, DiagnosticoForm, QuiropracticaForm, FisioterapiaForm, Peso, Medida, Quiropractica, \
    Fisioterapia
from clinica.models import Paciente, Doctor, Categoria, Historial
from utils.PermissionsMixim import GroupRequiredMixin
from utils.ResponseMixim import CreateFormResponseMixin, UpdateFormResponseMixin, JsonDeleteView


class PacientesListView(TemplateView):
    template_name = 'pascientes/list.html'


class PacientesListJson(BaseDatatableView):
    model = Paciente
    columns = ['id', 'nombre', 'apellido', 'direccion', 'estado']
    order_columns = ['id', 'nombre', 'apellido', 'direccion', 'estado']


class PacienteCreateView(CreateView, CreateFormResponseMixin):
    template_name = 'pascientes/create.html'
    model = Paciente
    form_class = PacienteForm


class PacienteUpdateView(UpdateView, UpdateFormResponseMixin):
    template_name = 'pascientes/update.html'
    model = Paciente
    form_class = PacienteForm


class PacienteDeleteJsonView(JsonDeleteView, GroupRequiredMixin):
    group_required = ['Administrador']
    model = Paciente

    def post(self, request, *args, **kwargs):
        super().post(request, args, kwargs)
        return JsonResponse({'result': 'OK', 'id': kwargs.get('pk')})


class PacienteInactivoJsonView(JsonDeleteView, GroupRequiredMixin):
    group_required = ['Administrador']
    model = Paciente

    def post(self, request, *args, **kwargs):
        paciente = Paciente.objects.get(pk=kwargs.get('pk'))
        if paciente.estado is 1:
            paciente.estado = 2
        else:
            paciente.estado = 1
        paciente.save()
        return JsonResponse({'result': 'OK', 'id': kwargs.get('pk')})


class PacienteDetallesView(DetailView):
    model = Paciente
    template_name = 'pascientes/details.html'


class DoctoresListView(TemplateView):
    template_name = 'doctores/list.html'


class DoctoresListJson(BaseDatatableView):
    model = Doctor
    columns = ['id', 'nombre', 'apellido', 'telefono', 'estado']
    order_columns = ['id', 'nombre', 'apellido', 'telefono', 'estado']


class DoctorCreateView(CreateView, CreateFormResponseMixin):
    template_name = 'doctores/create.html'
    model = Doctor
    form_class = DoctorForm


class DoctorUpdateView(UpdateView, UpdateFormResponseMixin):
    template_name = 'doctores/update.html'
    model = Doctor
    form_class = DoctorForm


class DoctorDeleteJsonView(JsonDeleteView):
    model = Doctor

    def post(self, request, *args, **kwargs):
        super().post(request, args, kwargs)
        return JsonResponse({'result': 'OK', 'id': kwargs.get('pk')})


class DoctorEstadoJsonView(JsonDeleteView, GroupRequiredMixin):
    group_required = ['Administrador']
    model = Doctor

    def post(self, request, *args, **kwargs):
        doctor = Doctor.objects.get(pk=kwargs.get('pk'))
        if doctor.estado is 1:
            doctor.estado = 2
        else:
            doctor.estado = 1
        doctor.save()
        return JsonResponse({'result': 'OK', 'id': kwargs.get('pk')})


class DoctorDetallesView(DetailView):
    model = Doctor
    template_name = 'doctores/details.html'


class CategoriasListView(TemplateView):
    template_name = 'categorias/list.html'


class CategoriasListJson(BaseDatatableView):
    model = Categoria
    columns = ['id', 'nombre']
    order_columns = ['id', 'nombre']


class CategoriaCreateView(CreateView, CreateFormResponseMixin):
    template_name = 'categorias/create.html'
    model = Categoria
    form_class = CategoriaForm


class CategoriaUpdateView(UpdateView, UpdateFormResponseMixin):
    template_name = 'categorias/update.html'
    model = Categoria
    form_class = CategoriaForm


class CategoriaDeleteJsonView(JsonDeleteView):
    model = Categoria

    def post(self, request, *args, **kwargs):
        super().post(request, args, kwargs)
        return JsonResponse({'result': 'OK', 'id': kwargs.get('pk')})


class CitasListView(TemplateView):
    template_name = 'citas/list.html'


class CitasListJson(BaseDatatableView):
    model = None
    columns = ['id', 'fecha', 'hora', 'categoria.nombre', 'paciente', 'doctor']
    order_columns = ['id', 'fecha', 'hora', 'categoria.nombre', 'paciente', 'doctor']

    def get_initial_queryset(self):
        return Cita.objects.all().order_by('-fecha').order_by('-hora__hours')


class CitaCreateView(CreateView, CreateFormResponseMixin):
    template_name = 'citas/create.html'
    model = Cita
    form_class = CitaForm


class CitaUpdateView(UpdateView, UpdateFormResponseMixin):
    template_name = 'citas/update.html'
    model = Cita
    form_class = CitaForm


class CitaDeleteJsonView(JsonDeleteView):
    model = Cita

    def post(self, request, *args, **kwargs):
        super().post(request, args, kwargs)
        return JsonResponse({'result': 'OK', 'id': kwargs.get('pk')})


class DiagnosticoNewView(CreateView, CreateFormResponseMixin):
    template_name = 'diagnosticos/create.html'
    model = Diagnostico
    form_class = DiagnosticoForm
    success_url = reverse_lazy('clinica:historial')

    def get_form(self, form_class=None):
        form = super(DiagnosticoNewView, self).get_form(form_class)
        cita = Cita.objects.get(pk=self.kwargs.get('cita_id'))
        form.initial = {
            'fecha': cita.fecha
        }
        return form

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        extra_quiropractica = extra_fisioterapia = extra_peso_medida = 0

        cita = Cita.objects.get(pk=self.kwargs.get('cita_id'))
        context['diagnostico'] = Diagnostico.objects.filter(cita_id=cita.id).count() > 0
        context['cita'] = cita
        context['paciente'] = cita.paciente
        if cita.categoria.nombre.lower() == 'quiropractica':
            extra_quiropractica = 1
        if cita.categoria.nombre.lower() == 'fisioterapia':
            extra_fisioterapia = 1
        if cita.categoria.nombre.lower() == 'peso y medida':
            extra_peso_medida = 1

        quiropractica_formset = formset_factory(QuiropracticaForm, extra=extra_quiropractica)
        context['formsetQuiropractica'] = quiropractica_formset(prefix='Quiropractica')

        fisioterapia_formset = formset_factory(FisioterapiaForm, extra=extra_fisioterapia)
        context['formsetFisioterapia'] = fisioterapia_formset(prefix='Fisioterapia')

        peso_formset = formset_factory(PesoForm, extra=extra_peso_medida)
        context['formsetPeso'] = peso_formset(prefix='Peso')
        medida_formset = formset_factory(MedidaForm, extra=extra_peso_medida)
        context['formsetMedida'] = medida_formset(prefix='Medida')
        return context

    def form_valid(self, form):
        extra_quiropractica = extra_fisioterapia = extra_peso_medida = 0
        cita = Cita.objects.get(pk=self.kwargs.get('cita_id'))
        if cita.categoria.nombre.lower() == 'quiropractica':
            extra_quiropractica = 1
        if cita.categoria.nombre.lower() == 'fisioterapia':
            extra_fisioterapia = 1
        if cita.categoria.nombre.lower() == 'peso y medida':
            extra_peso_medida = 1

        self.request.POST._mutable = True
        self.request.POST['Quiropractica-TOTAL_FORMS'] = extra_quiropractica
        self.request.POST['Fisioterapia-TOTAL_FORMS'] = extra_fisioterapia
        self.request.POST['Peso-TOTAL_FORMS'] = extra_peso_medida
        self.request.POST['Medida-TOTAL_FORMS'] = extra_peso_medida

        quiropractica_formset = formset_factory(QuiropracticaForm)
        formset_quiropractica = quiropractica_formset(self.request.POST, self.request.FILES, prefix='Quiropractica')

        fisioterapia_formset = formset_factory(FisioterapiaForm)
        formset_fisioterapia = fisioterapia_formset(self.request.POST, self.request.FILES, prefix='Fisioterapia')

        peso_formset = formset_factory(PesoForm)
        formset_peso = peso_formset(self.request.POST, self.request.FILES, prefix='Peso')
        medida_formset = formset_factory(MedidaForm)
        formset_medida = medida_formset(self.request.POST, self.request.FILES, prefix='Medida')

        with transaction.atomic():
            diagnostico = form.save(commit=False)
            diagnostico.usuario_id = self.request.user.pk
            diagnostico.cita_id = self.kwargs.get('cita_id')
            diagnostico.save()

            if formset_quiropractica.is_valid():
                for item in formset_quiropractica:
                    detalle = item.save(commit=False)
                    if detalle.precio_q is None:
                        detalle.precio_q = 0
                    detalle.diagnostico_id = diagnostico.pk
                    detalle.save()

            if formset_fisioterapia.is_valid():
                for item in formset_fisioterapia:
                    detalle = item.save(commit=False)
                    if detalle.precio_f is None:
                        detalle.precio_f = 1
                    detalle.diagnostico_id = diagnostico.pk
                    detalle.save()

            if formset_peso.is_valid():
                for item in formset_peso:
                    detalle = item.save(commit=False)
                    detalle.diagnostico_id = diagnostico.pk
                    detalle.save()

            if formset_medida.is_valid():
                for item in formset_medida:
                    detalle = item.save(commit=False)

clinica/templates/citas/create.html
{% url 'clinica:cita-create' as action_url %}
{% include "snippets/form-content.html" with action=action_url title='Nueva Cita' %}

clinica/templates/citas/list.html
{% extends 'base.html' %}}
{% load static from staticfiles %}

{% block css %}
    <link rel="stylesheet" href="{% static 'select2/dist/css/select2.min.css' %}">
    <link rel="stylesheet" href="{% static 'select2-bootstrap4-theme/dist/select2-bootstrap4.min.css' %}">
    <link rel="stylesheet" href="{% static 'datatables.net-bs4/css/dataTables.bootstrap4.css' %}">
    <link rel="stylesheet" href="{% static 'datatables.net-responsive-bs4/css/responsive.bootstrap4.min.css' %}">
    <link rel="stylesheet" href="{% static 'datatables.net-bs4/css/dataTables.bootstrap4.min.css' %}">
    <link rel="stylesheet" href="{% static 'inputmask/css/inputmask.css' %}">
{% endblock %}


{% block content %}
    <div class="card card-nav-tabs">
        <div class="card-header card-header-primary text-center">
            Citas
        </div>
        <div class="card-body">
            <h4 class="card-title pull-left">Listado</h4>
            {% url 'clinica:cita-create' as create_url %}
            {% include 'snippets/button-and-search.html' with create_url=create_url %}
            <table class="table table-bordered table-striped table-sm" id="data-table"></table>
        </div>
    </div>
    {% include 'snippets/modal-content.html' %}
{% endblock %}

{% block javascript %}
    <script type="text/javascript" charset="utf8" src="{% static 'datatables.net/js/jquery.dataTables.js' %}"></script>
    <script type="text/javascript" charset="utf8"
            src="{% static 'datatables.net-bs4/js/dataTables.bootstrap4.js' %}"></script>
    <script type="text/javascript" charset="utf8"
            src="{% static 'datatables.net-colreorder/js/dataTables.colReorder.min.js' %}"></script>
    <script type="text/javascript" charset="utf8"
            src="{% static 'datatables.net-responsive/js/dataTables.responsive.min.js' %}"></script>
    <script type="text/javascript" charset="utf8" src="{% static 'select2/dist/js/select2.min.js' %}"></script>
        <script type="text/javascript" charset="utf8"
            src="{% static 'inputmask/dist/min/jquery.inputmask.bundle.min.js' %}"></script>

    <!--suppress JSUnresolvedFunction -->
    <script src="{% static 'js/main.js' %}"></script>
    <script src="{% static 'js/dataTable.js' %}"></script>
    <script src="{% static 'js/requestForm.js' %}"></script>
    <!--suppress JSUnresolvedFunction -->
    <script type="text/javascript">
        // Sobreescribir urls para los botones
        urlEditar = "{% url 'clinica:cita-update' pk=0 %}";
        urlEliminar = "{% url 'clinica:cita-delete' pk=0 %}";

        function linkDiagnostico(url) {
            const link = `<a class="details-button btn btn-success btn-fab btn-icon btn-round btn-sm" title="Diagnostico" href="${url}"><i class="tim-icons icon-paper"></i></a>`;
            return `<div class="text-center">${link}</div>`;
        }

        function loadDataTable() {
            let url = "{% url 'clinica:citas-json' %}";
            let language_url = "{% static 'datatables-translate.json' %}";
            let columns = [
                {
                    data: '0',
                    title: 'Código',
                    responsivePriority: 1,
                    width: '15%',
                    visible: false
                },
                {
                    data: '1',
                    title: 'Fecha',
                    responsivePriority: 2,
                },
                {
                    data: '2',
                    title: 'Hora',
                    responsivePriority: 2
                },
                {
                    data: '3',
                    title: 'Categoria',
                    responsivePriority: 2
                },
                {
                    data: '4',
                    title: 'Paciente',
                    responsivePriority: 2,
                    searchable: false
                },
                {
                    data: '5',
                    title: 'Doctor',
                    responsivePriority: 2,
                    searchable: false
                },
                {
                    data: '0',
                    title: 'Acciones',
                    searchable: false,
                    sortable: false,
                    width: '18%',
                    responsivePriority: 3,
                    render: function (data, type, row) {
                        const url = "{% url 'clinica:diagnostico-new' cita_id=0 %}".replace('0', data);
                        return simpleBtns(data) + linkDiagnostico(url);
                    }
                }
            ];
            const conf = getDefaultDataTables(url, language_url, columns);
            conf.order = [[ 1, "asc" ], [ 2, "asc" ]];
            $table.DataTable(conf);
        }

        $(document).ready(function () {
            defaultConfig();
            loadDataTable()
        });
    </script>
{% endblock %}

clinica/templates/citas/update.html
{% url 'clinica:cita-update'  pk=object.id as action_url %}
{% include "snippets/form-content.html" with action=action_url title='Actualizar Cita' %}