catalogos/urls.py
from django.urls import path

from . import views

app_name = 'catalogos'
urlpatterns = [
    # Urls de usuarios
    path('users/', views.UsersListView.as_view(), name='users'),
    path('users/users-json/', views.UsersListJson.as_view(), name='users-json'),
    path('users/user-create/', views.UserCreateView.as_view(), name='user-create'),
    path('users/<int:pk>/user-update/', views.UserUpdateView.as_view(), name='user-update'),
    path('users/<int:pk>/delete-update/', views.UserDeleteJsonView.as_view(), name='user-delete'),

    # Urls de servicios
    path('servicios/', views.ServiciosListView.as_view(), name='servicios'),
    path('servicios/articulos-json/', views.ServiciosListJson.as_view(), name='servicios-json'),
    path('servicios/articulo-create/', views.ServicioCreateView.as_view(), name='servicio-create'),
    path('servicios/<int:pk>/articulo-update/', views.ServicioUpdateView.as_view(), name='servicio-update'),
    path('servicios/<int:pk>/articulo-delete/', views.ServicioDeleteJsonView.as_view(), name='servicio-delete'),

    # Urls de tipos de personal
    path('tipos-personal/', views.TiposPersonalListView.as_view(), name='tipos-personal'),
    path('tipos-personal/tipos-personal-json/', views.TiposPersonalListJson.as_view(), name='tipos-personal-json'),
    path('tipos-personal/tipo-personal-create/', views.TipoPersonalCreateView.as_view(), name='tipo-personal-create'),
    path('tipos-personal/<int:pk>/tipo-personal-update/', views.TipoPersonalUpdateView.as_view(),
         name='tipo-personal-update'),
    path('tipos-personal/<int:pk>/tipo-personal-delete/', views.TipoPersonalDeleteJsonView.as_view(),
         name='tipo-personal-delete'),

    # Urls de personal
    path('personal/', views.PersonalListView.as_view(), name='personal'),
    path('personal/personal-json/', views.PersonalListJson.as_view(), name='personal-json'),
    path('personal/personal-create/', views.PersonalCreateView.as_view(), name='personal-create'),
    path('personal/<int:pk>/personal-update/', views.PersonalUpdateView.as_view(),
         name='personal-update'),
    path('personal/<int:pk>/personal-delete/', views.PersonalDeleteJsonView.as_view(),
         name='personal-delete'),

    # Urls de jornadas
    path('jornadas/', views.JornadasListView.as_view(), name='jornadas'),
    path('jornadas/jornadas-json/', views.JornadasListJson.as_view(), name='jornadas-json'),
    path('jornadas/jornada-create/', views.JornadaCreateView.as_view(), name='jornada-create'),
    path('jornadas/<int:pk>/jornada-update/', views.JornadaUpdateView.as_view(),
         name='jornada-update'),
    path('jornadas/<int:pk>/jornada-delete/', views.JornadaDeleteJsonView.as_view(),
         name='jornada-delete'),

    # Urls de dietas
    path('dietas/', views.DietasListView.as_view(), name='dietas'),
    path('dietas/dietas-json/', views.DietasListJson.as_view(), name='dietas-json'),
    path('dietas/dieta-create/', views.DietaCreateView.as_view(), name='dieta-create'),
    path('dietas/<int:pk>/dieta-update/', views.DietaUpdateView.as_view(), name='dieta-update'),
    path('dietas/<int:pk>/dieta-delete/', views.DietaDeleteJsonView.as_view(), name='dieta-delete'),
]

clinica/urls.py
from django.urls import path

from . import views

app_name = 'clinica'
urlpatterns = [
    # Urls de pacientes
    path('pacientes/', views.PacientesListView.as_view(), name='pacientes'),
    path('pacientes/pacientes-json/', views.PacientesListJson.as_view(), name='pacientes-json'),
    path('pacientes/paciente-create/', views.PacienteCreateView.as_view(), name='paciente-create'),
    path('pacientes/<int:pk>/paciente-update/', views.PacienteUpdateView.as_view(), name='paciente-update'),
    path('pacientes/<int:pk>/paciente-delete/', views.PacienteDeleteJsonView.as_view(), name='paciente-delete'),
    path('pacientes/<int:pk>/paciente-details/', views.PacienteDetallesView.as_view(), name='paciente-details'),
    path('pacientes/<int:pk>/paciente-inactivo/', views.PacienteInactivoJsonView.as_view(), name='paciente-inactivo'),

    # Urls de doctores
    path('doctores/', views.DoctoresListView.as_view(), name='doctores'),
    path('doctores/doctores-json/', views.DoctoresListJson.as_view(), name='doctores-json'),
    path('doctores/doctor-create/', views.DoctorCreateView.as_view(), name='doctor-create'),
    path('doctores/<int:pk>/menu-update/', views.DoctorUpdateView.as_view(), name='doctor-update'),
    path('doctores/<int:pk>/delete-update/', views.DoctorDeleteJsonView.as_view(), name='doctor-delete'),
    path('doctores/<int:pk>/doctore-details/', views.DoctorDetallesView.as_view(), name='doctor-details'),
    path('doctores/<int:pk>/doctore-estado/', views.DoctorEstadoJsonView.as_view(), name='doctor-estado'),
    # Urls de menus
    path('categorias/', views.CategoriasListView.as_view(), name='categorias'),
    path('categorias/categorias-json/', views.CategoriasListJson.as_view(), name='categorias-json'),
    path('categorias/categoria-create/', views.CategoriaCreateView.as_view(), name='categoria-create'),
    path('categorias/<int:pk>/categoria-update/', views.CategoriaUpdateView.as_view(), name='categoria-update'),
    path('categorias/<int:pk>/cateogria-delete/', views.CategoriaDeleteJsonView.as_view(), name='categoria-delete'),

    # Urls de citas
    path('citas/', views.CitasListView.as_view(), name='citas'),
    path('citas/citas-json/', views.CitasListJson.as_view(), name='citas-json'),
    path('citas/cita-create/', views.CitaCreateView.as_view(), name='cita-create'),
    path('citas/<int:pk>/menu-update/', views.CitaUpdateView.as_view(), name='cita-update'),
    path('citas/<int:pk>/delete-update/', views.CitaDeleteJsonView.as_view(),
         name='cita-delete'),

    # Urls de Diagnosticos
    path('diagnosticos/<int:cita_id>/diagnostico-new/', views.DiagnosticoNewView.as_view(), name='diagnostico-new'),
    path('diagnosticos/<int:pk>/diagnostico-detatils/', views.DiagnosticoDetailsView.as_view(),
         name='diagnostico-details'),

    # Urls de historial
    path('historial/', views.HistorialListView.as_view(), name='historial'),
    path('historial/historial-json/', views.HistorialListJson.as_view(), name='historial-json'),
]

nutricion_igss/urls.py
from django.contrib import admin
from django.contrib.auth.views import LoginView
from django.urls import path, include

from nutricion_igss import views
from catalogos import urls as catalogos_urls
from clinica import urls as clinica_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('login/', LoginView.as_view()),
    path('', views.index, name='index'),
    path('', include(catalogos_urls)),
    path('', include(clinica_urls)),
]

templates/base.html
{% load static from staticfiles %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="apple-touch-icon" sizes="76x76" href="{% static 'assets/img/apple-icon.png' %}">
    <title>
        Clinica
    </title>
    <!--     Fonts and icons     -->
    <link href="https://fonts.googleapis.com/css?family=Poppins:200,300,400,600,700,800" rel="stylesheet"/>
    <link href="https://use.fontawesome.com/releases/v5.0.6/css/all.css" rel="stylesheet">
    <!-- Nucleo Icons -->
    <link href="{% static 'assets/css/nucleo-icons.css' %}" rel="stylesheet"/>
    <!-- CSS Files -->
    <link href="{% static 'assets/css/black-dashboard.css' %}" rel="stylesheet"/>
    <!-- include the style -->
    <link rel="stylesheet" href="{% static 'alertifyjs/build/css/alertify.min.css' %}"/>
    <!-- include a theme -->
    <link rel="stylesheet" href="{% static 'alertifyjs/build/css/themes/default.min.css' %}"/>
    {% block css %}
    {% endblock %}
</head>

<body class="">
<div class="wrapper">
    {% include 'sidebar.html' %}
    <div class="main-panel">
        <!-- Navbar -->
        <nav class="navbar navbar-expand-lg navbar-absolute navbar-transparent">
            <div class="container-fluid">
                <div class="navbar-wrapper">
                    <div class="navbar-toggle d-inline">
                        <button type="button" class="navbar-toggler">
                            <span class="navbar-toggler-bar bar1"></span>
                            <span class="navbar-toggler-bar bar2"></span>
                            <span class="navbar-toggler-bar bar3"></span>
                        </button>
                    </div>
                </div>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navigation"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-bar navbar-kebab"></span>
                    <span class="navbar-toggler-bar navbar-kebab"></span>
                    <span class="navbar-toggler-bar navbar-kebab"></span>
                </button>
                <div class="collapse navbar-collapse" id="navigation">
                    <ul class="navbar-nav ml-auto">
                        <li class="search-bar input-group">

                        </li>

                        <li class="dropdown nav-item">
                            <a href="{% url 'logout' %}" class="dropdown-toggle nav-link" data-toggle="dropdown">
                                <div class="photo">
                                    <img src="{% static 'assets/img/anime3.png' %}" alt="Profile Photo">
                                </div>
                                <strong class="caret d-none d-lg-block d-xl-block"></strong>
                                <p class="d-lg-none">
                                    Cerrar Sesión
                                </p>
                            </a>
                            <ul class="dropdown-menu dropdown-navbar">
                                <li class="nav-link"><a href="javascript:void(0)"
                                                        class="nav-item dropdown-item">Perfil</a></li>
                                <li class="dropdown-divider"></li>
                                <li class="nav-link"><a href="{% url 'logout' %}" class="nav-item dropdown-item">Cerrar
                                    Sesión</a></li>
                            </ul>
                        </li>
                        <li class="separator d-lg-none"></li>
                    </ul>
                </div>
            </div>
        </nav>
        <div class="modal modal-search fade" id="searchModal" tabindex="-1" role="dialog" aria-labelledby="searchModal"
             aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <input type="text" class="form-control" id="inlineFormInputGroup" placeholder="Buscar">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <i class="tim-icons icon-simple-remove"></i>
                        </button>
                    </div>
                </div>
            </div>
        </div>
        <!-- End Navbar -->
        <div class="content">
            {% if messages %}
                {% for message in messages %}
                    <div class="alert {{ message.tags }}">
                        <button type="button" aria-hidden="true" class="close" data-dismiss="alert" aria-label="Close">
                            <i class="tim-icons icon-simple-remove"></i>
                        </button>
                        <span><b>{{ message }}</b></span>
                    </div>
                {% endfor %}
            {% endif %}
            {% block content %}
            {% endblock %}
        </div>
        <footer class="footer">
            <div class="container-fluid">
                <ul class="nav">
                    <li class="nav-item">
                        <a href="javascript:void(0)" class="nav-link">
                        </a>
                    </li>
                </ul>
                <script>
                </script>&nbsp;
            </div>
    </div>
    </footer>
</div>
</div>


<!--   Core JS Files   -->
<script src="{% static 'assets/js/core/jquery.min.js' %}" type="text/javascript"></script>
<script src="{% static 'assets/js/core/popper.min.js' %}" type="text/javascript"></script>
<script src="{% static 'assets/js/core/bootstrap.min.js' %}" type="text/javascript"></script>
<script src="{% static 'assets/js/plugins/perfect-scrollbar.jquery.min.js' %}" type="text/javascript"></script>
<!-- Chartist JS -->
<script src="{% static 'assets/js/plugins/chartjs.min.js' %}"></script>
<!--  Notifications Plugin    -->
<script src="{% static 'assets/js/plugins/bootstrap-notify.js' %}"></script>
<!-- Control Center for Material Dashboard: parallax effects, scripts for the example pages etc -->
<script src="{% static 'assets/js/black-dashboard.js' %}" type="text/javascript"></script>
<script src="{% static 'assets/demo/demo.js' %}"></script>
<script>
    $(document).ready(function () {
        $().ready(function () {
            $sidebar = $('.sidebar');
            $navbar = $('.navbar');
            $main_panel = $('.main-panel');

            $full_page = $('.full-page');

            $sidebar_responsive = $('body > .navbar-collapse');
            sidebar_mini_active = true;
            white_color = false;

            window_width = $(window).width();

            fixed_plugin_open = $('.sidebar .sidebar-wrapper .nav li.active a p').html();

            $('.fixed-plugin a').click(function (event) {
                if ($(this).hasClass('switch-trigger')) {
                    if (event.stopPropagation) {
                        event.stopPropagation();
                    } else if (window.event) {
                        window.event.cancelBubble = true;
                    }
                }
            });
            var new_color = 'green';
            $sidebar.attr('data', new_color);
            $main_panel.attr('data', new_color);
            $full_page.attr('filter-color', new_color);
            $sidebar_responsive.attr('data', new_color);

            $('.fixed-plugin .background-color span').click(function () {
                $(this).siblings().removeClass('active');
                $(this).addClass('active');

                var new_color = $(this).data('color');

                if ($sidebar.length != 0) {
                    $sidebar.attr('data', new_color);
                }

                if ($main_panel.length != 0) {
                    $main_panel.attr('data', new_color);
                }

                if ($full_page.length != 0) {
                    $full_page.attr('filter-color', new_color);
                }

                if ($sidebar_responsive.length != 0) {
                    $sidebar_responsive.attr('data', new_color);
                }
            });

            // update theme
            $(".background-color .active").trigger('click');
            $('body').addClass('white-content');

            $('.switch-sidebar-mini input').on("switchChange.bootstrapSwitch", function () {
                var $btn = $(this);

                if (sidebar_mini_active == true) {
                    $('body').removeClass('sidebar-mini');
                    sidebar_mini_active = false;
                    blackDashboard.showSidebarMessage('Sidebar mini deactivated...');
                } else {
                    $('body').addClass('sidebar-mini');
                    sidebar_mini_active = true;
                    blackDashboard.showSidebarMessage('Sidebar mini activated...');
                }

                // we simulate the window Resize so the charts will get updated in realtime.
                var simulateWindowResize = setInterval(function () {
                    window.dispatchEvent(new Event('resize'));
                }, 180);

                // we stop the simulation of Window Resize after the animations are completed
                setTimeout(function () {
                    clearInterval(simulateWindowResize);
                }, 1000);
            });

            $('.switch-change-color input').on("switchChange.bootstrapSwitch", function () {
                var $btn = $(this);

                if (white_color == true) {

                    $('body').addClass('change-background');
                    setTimeout(function () {
                        $('body').removeClass('change-background');
                        $('body').removeClass('white-content');
                    }, 900);
                    white_color = false;
                } else {

                    $('body').addClass('change-background');
                    setTimeout(function () {
                        $('body').removeClass('change-background');
                        $('body').addClass('white-content');
                    }, 900);

                    white_color = true;
                }


            });

            $('.light-badge').click(function () {
                $('body').addClass('white-content');
            });

            $('.dark-badge').click(function () {
                $('body').removeClass('white-content');
            });
        });
    });
</script>
<script src="{% static 'sweetalert2/dist/sweetalert2.all.min.js' %}" type="text/javascript"></script>
<script src="{% static 'toastr/build/toastr.min.js' %}" type="text/javascript"></script>
<script src="{% static 'alertifyjs/build/alertify.min.js' %}" type="text/javascript"></script>
{% block javascript %}

{% endblock %}
</body>
</html>

templates/index.html
{% extends 'base.html' %}
{% load static from staticfiles %}

{% block content %}
    {% if user.is_authenticated %}
        <div class="alert alert-success">
            <button type="button" aria-hidden="true" class="close" data-dismiss="alert" aria-label="Close">
                <i class="tim-icons icon-simple-remove"></i>
            </button>
            <span><b> Bienvenido <strong>{{ user.username }}</strong></b></span>
        </div>
        <div class="row text-success m-5 p-5   ">
            <img src="{% static 'assets/img/logo.jpeg' %}" alt="">
            <h1 class="ml-2 text-success text-uppercase">Bienvenido Benestar Clinica Xela</h1>
        </div>
    {% endif %}

{% endblock %}

{% block javascript %}

    <script>
        function closeMessageWelcome() {
            $('.alert').alert('close')
        }

        $(document).ready(function () {
            setTimeout(closeMessageWelcome, 3000);
        });
    </script>
{% endblock %}

templates/sidebar.html
{% load auth_extras %}

<div class="sidebar">
    {% if request.user|has_group:"Administrador"%}
            <div class="sidebar-wrapper">
        <div class="logo">
            <a href="javascript:void(0)" class="simple-text logo-mini">
            </a>
            <a href="javascript:void(0)" class="simple-text logo-normal">
                Clinica
            </a>
        </div>
        <ul class="nav">
            <li class="active ">
                <a href="{% url 'index' %}">
                    <i class="tim-icons icon-chart-pie-36"></i>
                    <p>Inicio</p>
                </a>
            </li>
            <li>
                <a href="{% url 'clinica:citas' %}">
                    <i class="tim-icons icon-bullet-list-67"></i>
                    <p>Citas</p>
                </a>
            </li>
            <li>
                <a href="{% url 'clinica:categorias' %}">
                    <i class="tim-icons icon-bullet-list-67"></i>
                    <p>Categorias</p>
                </a>
            </li>
            <li>
                <a href="{% url 'clinica:historial' %}">
                    <i class="tim-icons icon-bullet-list-67"></i>
                    <p>Historial</p>
                </a>
            </li>
            <li>
                <a href="{% url 'clinica:doctores' %}">
                    <i class="tim-icons icon-bullet-list-67"></i>
                    <p>Doctores</p>
                </a>
            </li>
            <li>
                <a href="{% url 'clinica:pacientes' %}">
                    <i class="tim-icons icon-bullet-list-67"></i>
                    <p>Pacientes</p>
                </a>
            </li>
            <li>
                <a href="{% url 'catalogos:users' %}">
                    <i class="tim-icons icon-single-02"></i>
                    <p>Usuarios</p>
                </a>
            </li>
        </ul>
    </div>
    {% endif %}
    {% if request.user|has_group:"Asistente"%}
            <div class="sidebar-wrapper">
        <div class="logo">
            <a href="javascript:void(0)" class="simple-text logo-mini">

            </a>
            <a href="javascript:void(0)" class="simple-text logo-normal">
                Clinica
            </a>
        </div>
        <ul class="nav">
            <li class="active">
                <a href="{% url 'index' %}">
                    <i class="tim-icons icon-chart-pie-36"></i>
                    <p>Home</p>
                </a>
            </li>
            <li>
                <a href="{% url 'clinica:citas' %}">
                    <i class="tim-icons icon-bullet-list-67"></i>
                    <p>Citas</p>
                </a>
            </li>
            <li>
                <a href="{% url 'clinica:pacientes' %}">
                    <i class="tim-icons icon-bullet-list-67"></i>
                    <p>Pacientes</p>
                </a>
            </li>
        </ul>
    </div>
    {% endif %}
</div>