clinica/urls.py
from django.urls import path

from . import views

app_name = 'clinica'
urlpatterns = [
    # Urls de pacientes
    path('pacientes/', views.PacientesListView.as_view(), name='pacientes'),
    path('pacientes/pacientes-json/', views.PacientesListJson.as_view(), name='pacientes-json'),
    path('pacientes/paciente-create/', views.PacienteCreateView.as_view(), name='paciente-create'),
    path('pacientes/<int:pk>/paciente-update/', views.PacienteUpdateView.as_view(), name='paciente-update'),
    path('pacientes/<int:pk>/paciente-delete/', views.PacienteDeleteJsonView.as_view(), name='paciente-delete'),
    path('pacientes/<int:pk>/paciente-details/', views.PacienteDetallesView.as_view(), name='paciente-details'),
    path('pacientes/<int:pk>/paciente-inactivo/', views.PacienteInactivoJsonView.as_view(), name='paciente-inactivo'),

    # Urls de doctores
    path('doctores/', views.DoctoresListView.as_view(), name='doctores'),
    path('doctores/doctores-json/', views.DoctoresListJson.as_view(), name='doctores-json'),
    path('doctores/doctor-create/', views.DoctorCreateView.as_view(), name='doctor-create'),
    path('doctores/<int:pk>/menu-update/', views.DoctorUpdateView.as_view(), name='doctor-update'),
    path('doctores/<int:pk>/delete-update/', views.DoctorDeleteJsonView.as_view(), name='doctor-delete'),
    path('doctores/<int:pk>/doctore-details/', views.DoctorDetallesView.as_view(), name='doctor-details'),
    path('doctores/<int:pk>/doctore-estado/', views.DoctorEstadoJsonView.as_view(), name='doctor-estado'),
    # Urls de menus
    path('categorias/', views.CategoriasListView.as_view(), name='categorias'),
    path('categorias/categorias-json/', views.CategoriasListJson.as_view(), name='categorias-json'),
    path('categorias/categoria-create/', views.CategoriaCreateView.as_view(), name='categoria-create'),
    path('categorias/<int:pk>/categoria-update/', views.CategoriaUpdateView.as_view(), name='categoria-update'),
    path('categorias/<int:pk>/cateogria-delete/', views.CategoriaDeleteJsonView.as_view(), name='categoria-delete'),

    # Urls de citas
    path('citas/', views.CitasListView.as_view(), name='citas'),
    path('citas/citas-json/', views.CitasListJson.as_view(), name='citas-json'),
    path('citas/cita-create/', views.CitaCreateView.as_view(), name='cita-create'),
    path('citas/<int:pk>/menu-update/', views.CitaUpdateView.as_view(), name='cita-update'),
    path('citas/<int:pk>/delete-update/', views.CitaDeleteJsonView.as_view(),
         name='cita-delete'),

    # Urls de Diagnosticos
    path('diagnosticos/<int:cita_id>/diagnostico-new/', views.DiagnosticoNewView.as_view(), name='diagnostico-new'),
    path('diagnosticos/<int:pk>/diagnostico-detatils/', views.DiagnosticoDetailsView.as_view(),
         name='diagnostico-details'),

    # Urls de historial
    path('historial/', views.HistorialListView.as_view(), name='historial'),
    path('historial/historial-json/', views.HistorialListJson.as_view(), name='historial-json'),
]

nutricion_igss/urls.py
from django.contrib import admin
from django.contrib.auth.views import LoginView
from django.urls import path, include

from nutricion_igss import views
from catalogos import urls as catalogos_urls
from clinica import urls as clinica_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('login/', LoginView.as_view()),
    path('', views.index, name='index'),
    path('', include(catalogos_urls)),
    path('', include(clinica_urls)),
]

clinica/models.py
from django.contrib.auth.models import User
from django.db import models
from django_extensions.db.models import TimeStampedModel


class Paciente(TimeStampedModel):
    Genero = (
        (1, 'Hombre'),
        (2, 'Mujer')
    )

    Estado = (
        (1, 'Activo'),
        (2, 'Inactivo')
    )

    nombre = models.CharField(max_length=100, verbose_name='Nombre')
    apellido = models.CharField(max_length=100, verbose_name='Apellido')
    direccion = models.CharField(max_length=200, verbose_name='Dirección')
    telefono = models.CharField(max_length=100, verbose_name='Telefono')
    edad = models.CharField(max_length=100, verbose_name='Edad', null=True, blank=True)
    dpi = models.CharField(max_length=100, verbose_name='Correo', null=True, blank=True)
    genero = models.SmallIntegerField(choices=Genero, verbose_name='Género')
    estado = models.SmallIntegerField(choices=Estado, default=1, verbose_name='Estado')

    class Meta:
        app_label = 'clinica'
        verbose_name = 'paciente'
        verbose_name_plural = 'pacientes'

    def __str__(self):
        return '%s %s ' % (self.nombre, self.apellido)


class Doctor(TimeStampedModel):
    Estado = (
        (1, 'Activo'),
        (2, 'Inactivo')
    )

    nombre = models.CharField(max_length=100, verbose_name='Nombre(s)')
    apellido = models.CharField(max_length=100, verbose_name='Apellido(s)')
    telefono = models.CharField(max_length=100, verbose_name='Teléfono')
    estado = models.SmallIntegerField(choices=Estado, default=1, verbose_name='Estado')

    class Meta:
        app_label = 'clinica'
        verbose_name = 'doctor'
        verbose_name_plural = 'doctor'

    def __str__(self):
        return '%s %s ' % (self.nombre, self.apellido)


class Categoria(models.Model):
    nombre = models.CharField(max_length=100, verbose_name='Nombre')

    class Meta:
        app_label = 'clinica'
        verbose_name = 'categoria'
        verbose_name_plural = 'categorias'

    def __str__(self):
        return self.nombre


class Cita(TimeStampedModel):
    fecha = models.DateField(verbose_name='Fecha')
    hora = models.TimeField(verbose_name='Hora')
    categoria = models.ForeignKey(Categoria, verbose_name='Categoria', related_name='categoria_cita',
                                  on_delete=models.PROTECT)
    doctor = models.ForeignKey(Doctor, verbose_name='Doctor', related_name='doctor_cita', on_delete=models.PROTECT)
    paciente = models.ForeignKey(Paciente, verbose_name='Paciente', related_name='paciente_cita',
                                 on_delete=models.PROTECT)

    class Meta:
        app_label = 'clinica'
        verbose_name = 'cita'
        verbose_name_plural = 'citas'

    def __str__(self):
        return str(self.fecha)


class Diagnostico(models.Model):
    fecha = models.DateField(verbose_name='Fecha')
    diagnostico = models.TextField(max_length=2000, verbose_name='Diagnostico')
    reseta = models.TextField(max_length=2000, verbose_name='Reseta')
    domingo = models.TextField(max_length=1000, verbose_name='Domingo', null=True, blank=True)
    lunes = models.TextField(max_length=1000, verbose_name='Lunes', null=True, blank=True)
    martes = models.TextField(max_length=1000, verbose_name='Martes', null=True, blank=True)
    miercoles = models.TextField(max_length=1000, verbose_name='Miercoles', null=True, blank=True)
    jueves = models.TextField(max_length=1000, verbose_name='Jueves', null=True, blank=True)
    viernes = models.TextField(max_length=1000, verbose_name='Viernes', null=True, blank=True)
    sabado = models.TextField(max_length=1000, verbose_name='Sabado', null=True, blank=True)

    usuario = models.ForeignKey(User, verbose_name='Usuario', related_name='usuario_diagnostico',
                                on_delete=models.PROTECT)
    cita = models.ForeignKey(Cita, verbose_name='Cita', related_name='cita_diagnostico', on_delete=models.PROTECT)

    class Meta:
        app_label = 'clinica'
        verbose_name = 'diagnostico'
        verbose_name_plural = 'diagnosticos'


class Peso(models.Model):
    peso = models.DecimalField(verbose_name='Peso', decimal_places=4, max_digits=18, default=0, null=True)
    estatura = models.DecimalField(verbose_name='Estatura', decimal_places=4, max_digits=18, default=0, null=True)
    imc = models.DecimalField(verbose_name='IMC', decimal_places=4, max_digits=18, default=0, null=True)
    grasa = models.PositiveIntegerField(verbose_name='Grasa', null=True)
    agua = models.PositiveIntegerField(verbose_name='Agua', null=True)
    masa_muscular = models.PositiveIntegerField(verbose_name='Masa Muscular', null=True)
    complexion_fisica = models.PositiveIntegerField(verbose_name='Complexion Fisica', null=True)
    metabolismo_basal = models.PositiveIntegerField(verbose_name='Metabolismo Basal', null=True)
    edad_metabolica = models.PositiveIntegerField(verbose_name='Edad Metabolica', null=True)
    masa_osea = models.PositiveIntegerField(verbose_name='Masa Osea', null=True)

    diagnostico = models.ForeignKey(Diagnostico, verbose_name='Diagnostico', related_name='diagnostico_peso',
                                    on_delete=models.PROTECT)

    class Meta:
        app_label = 'clinica'
        verbose_name = 'peso'
        verbose_name_plural = 'peso'

    def __str__(self):
        return self.peso


class Medida(models.Model):
    abdomen_superior = models.PositiveIntegerField(verbose_name='Abdomen Superior', null=True)
    cintura = models.PositiveIntegerField(verbose_name='Cintura', null=True)
    abdomen_inferior = models.PositiveIntegerField(verbose_name='Abdomen Inferior', null=True)
    circunferencia_brazo = models.PositiveIntegerField(verbose_name='Circunferencia Brazo', null=True)
    circunferencia_muslo = models.PositiveIntegerField(verbose_name='Circunferencia Muslo', null=True)

    diagnostico = models.ForeignKey(Diagnostico, verbose_name='Diagnostico', related_name='diagnostico_medida',
                                    on_delete=models.PROTECT)

    class Meta:
        app_label = 'clinica'
        verbose_name = 'medida'
        verbose_name_plural = 'medida'

    def __str__(self):
        return self.abdomen_superior


class Quiropractica(models.Model):
    precio_q = models.DecimalField(max_digits=18, decimal_places=4, verbose_name='Precio')
    diagnostico = models.ForeignKey(Diagnostico, verbose_name='Diagnostico', related_name='diagnostico_quiropractica',
                                    on_delete=models.PROTECT)

    class Meta:
        app_label = 'clinica'
        verbose_name = 'quiropractica'
        verbose_name_plural = 'quiropractica'

    def __str__(self):
        return self.precio


class Fisioterapia(models.Model):
    precio_f = models.DecimalField(max_digits=18, decimal_places=4, verbose_name='Precio')
    diagnostico = models.ForeignKey(Diagnostico, verbose_name='Diagnostico', related_name='diagnostico_fisioterapia',
                                    on_delete=models.PROTECT)

    class Meta:
        app_label = 'clinica'
        verbose_name = 'fisioterapia'
        verbose_name_plural = 'fisioterapia'

    def __str__(self):
        return self.precio


class Historial(TimeStampedModel):
    diagnostico = models.ForeignKey(Diagnostico, verbose_name='Diagnostico', related_name='diagnostico_historial',
                                    on_delete=models.PROTECT)
    usuario = models.ForeignKey(User, verbose_name='Usuario', related_name='usuario_historial',
                                on_delete=models.PROTECT)
    cita = models.ForeignKey(Cita, verbose_name='Cita', related_name='cita_historial', on_delete=models.PROTECT,
                             null=True, blank=True)

    class Meta:
        app_label = 'clinica'
        verbose_name = 'historial'
        verbose_name_plural = 'historial'

clinica/forms/formularios.py
from clinica.models import Paciente, Doctor, Cita, Categoria, Diagnostico, Medida, Peso, Fisioterapia, Quiropractica
from utils.FormMixim import FieldSetModelFormMixin, LargeFormMixin


class PacienteForm(FieldSetModelFormMixin):
    class Meta:
        model = Paciente
        fields = [
            'nombre', 'apellido', 'direccion', 'telefono', 'edad', 'dpi', 'genero'
        ]


class DoctorForm(FieldSetModelFormMixin):
    class Meta:
        model = Doctor
        fields = '__all__'


class CategoriaForm(FieldSetModelFormMixin):
    class Meta:
        model = Categoria
        fields = '__all__'


class CitaForm(FieldSetModelFormMixin):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['paciente'].queryset = Paciente.objects.filter(estado=1)
        self.fields['doctor'].queryset = Doctor.objects.filter(estado=1)

        self.fields['paciente'].widget.attrs['class'] = "select2"

    class Meta:
        model = Cita
        fields = '__all__'


class PesoForm(FieldSetModelFormMixin):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['imc'].widget.attrs['readonly'] = True
        self.fields['peso'].widget.attrs['step'] = "1"
        self.fields['peso'].widget.attrs['min'] = "0"
        self.fields['estatura'].widget.attrs['step'] = "1"
        self.fields['estatura'].widget.attrs['min'] = "0"

    class Meta:
        model = Peso
        fields = [
            'peso', 'estatura', 'imc', 'grasa', 'agua', 'masa_muscular', 'complexion_fisica', 'metabolismo_basal',
            'edad_metabolica', 'masa_osea'
        ]


class MedidaForm(FieldSetModelFormMixin):
    class Meta:
        model = Medida
        fields = ['abdomen_superior', 'cintura', 'abdomen_inferior', 'circunferencia_brazo',
                  'circunferencia_muslo']


class FisioterapiaForm(FieldSetModelFormMixin):
    class Meta:
        model = Fisioterapia
        fields = ['precio_f']


class QuiropracticaForm(FieldSetModelFormMixin):
    class Meta:
        model = Quiropractica
        fields = ['precio_q']


class DiagnosticoForm(LargeFormMixin):
    class Meta:
        model = Diagnostico
        fields = ['id', 'fecha', 'diagnostico', 'reseta', 'lunes', 'martes', 'miercoles', 'jueves', 'viernes', 'sabado',
                  'domingo']

clinica/templates/pascientes/create.html
{% url 'clinica:paciente-create' as action_url %}
{% include "snippets/form-content.html" with action=action_url title='Nuevo Paciente' %}

clinica/templates/pascientes/details.html
<div class="modal-header">
    <h5 class="modal-title">Detalles</h5>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times</span>
    </button>
</div>
<div class="modal-body">
    <h5><strong>Nombre: </strong>{{ object.nombre }}</h5>
    <h5><strong>Apellido: </strong>{{ object.apellido }}</h5>
    <h5><strong>Dirección: </strong>{{ object.direccion }}</h5>
    <h5><strong>Teléfono: </strong>{{ object.telefono }}</h5>
    <h5><strong>Edad: </strong>{{ object.edad }}</h5>
    <h5><strong>Correo Electronico: </strong>{{ object.dpi }}</h5>
    <h5><strong>Género: </strong>{{ object.get_genero_display}}</h5>
    <h5><strong>Estado: </strong>{{ object.get_estado_display}}</h5>

</div>

clinica/templates/pascientes/list.html
{% extends 'base.html' %}}
{% load static from staticfiles %}

{% block css %}
    <link rel="stylesheet" href="{% static 'datatables.net-bs4/css/dataTables.bootstrap4.css' %}">
    <link rel="stylesheet" href="{% static 'datatables.net-responsive-bs4/css/responsive.bootstrap4.min.css' %}">
    <link rel="stylesheet" href="{% static 'datatables.net-bs4/css/dataTables.bootstrap4.min.css' %}">
{% endblock %}

{% block content %}
    <div class="card card-nav-tabs">
        <div class="card-header card-header-primary text-center">
            Pascientes
        </div>
        <div class="card-body">
            <h4 class="card-title pull-left">Listado</h4>
            {% url 'clinica:paciente-create' as create_url %}
            {% include 'snippets/button-and-search.html' with create_url=create_url %}
            <table class="table table-bordered table-striped table-sm" id="data-table"></table>
        </div>
    </div>
    {% include 'snippets/modal-content.html' %}
{% endblock %}

{% block javascript %}
    <script type="text/javascript" charset="utf8" src="{% static 'datatables.net/js/jquery.dataTables.js' %}"></script>
    <script type="text/javascript" charset="utf8"
            src="{% static 'datatables.net-bs4/js/dataTables.bootstrap4.js' %}"></script>
    <script type="text/javascript" charset="utf8"
            src="{% static 'datatables.net-colreorder/js/dataTables.colReorder.min.js' %}"></script>
    <script type="text/javascript" charset="utf8"
            src="{% static 'datatables.net-responsive/js/dataTables.responsive.min.js' %}"></script>
    <!--suppress JSUnresolvedFunction -->
    <script src="{% static 'js/main.js' %}"></script>
    <script src="{% static 'js/dataTable.js' %}"></script>
    <script src="{% static 'js/requestForm.js' %}"></script>
    <!--suppress JSUnresolvedFunction -->
    <script type="text/javascript">
        // Sobreescribir urls para los botones
        urlEditar = "{% url 'clinica:paciente-update' pk=0 %}";
        urlEliminar = "{% url 'clinica:paciente-delete' pk=0 %}";
        urlDetalles = "{% url 'clinica:paciente-details' pk=0 %}";
        const urlInactivo = "{% url 'clinica:paciente-inactivo' pk=0 %}";

        function cambiarEstado(url, datatable) {
            swal({
                title: '¿Desea cambiar el estado del paciente?',
                type: 'warning',
                showCancelButton: true,
                confirmButtonText: '¡Si!',
                cancelButtonText: 'Cancelar',
                confirmButtonColor: '#d33',
                confirmButtonClass: 'btn btn-danger'
            }).then(function (result) {
                if (result.value) {
                    $.ajax({
                        url: url,
                        method: 'POST',
                        headers: {'X-CSRFToken': getCookie('csrftoken')},
                        success: function (data) {
                            if (data.result === 'OK') {
                                success_function();
                                swal("¡Completado!", "Se ha actualizado el registro.", "success");
                                datatable.DataTable().ajax.reload(null, false);
                            } else {
                                swal("Error", "¡Ha ocurrido un error inesperado al realizar la petición!", "error");
                            }
                        },
                        error: function (error) {
                            swal("Error", "", "error");
                            let message = '¡Ocurrio un error inesperado al intentar modificar el registro!';
                            if (error.responseJSON) {
                                message = error.responseJSON.result;
                            }
                            swal("Error", message, "error");
                        }
                    });
                }
            });
        }

        function inactivoBtn(data) {
            const url = `${urlInactivo.replace("0", data)}`;
            const btn = `<button class="estado-button btn btn-warning btn-fab btn-icon btn-round btn-sm" title="Cambiar Estado" data-url="${url}"><i class="tim-icons icon-refresh-02"></i></button>`;
            return `<div class="">${btn}</div>`;
        }

        $table.on('click', '.estado-button', function () {
            const url = $(this).data('url');
            cambiarEstado(url, $table);
        });

        function linkHistorial(url){
            const link = `<a class="details-button btn btn-primary btn-fab btn-icon btn-round btn-sm" title="Historial de Diagnosticos" href="${url}"><i class="tim-icons icon-chart-pie-36"></i></a>`;
            return `<div class="">${link}</div>`;
        }

        function loadDataTable() {
            let url = "{% url 'clinica:pacientes-json' %}";
            let language_url = "{% static 'datatables-translate.json' %}";
            let columns = [
                {
                    data: '0',
                    title: 'Código',
                    responsivePriority: 1,
                    width: '15%',
                },
                {
                    data: '1',
                    title: 'Nombre',
                    responsivePriority: 2,
                },
                {
                    data: '2',
                    title: 'Apellido',
                    responsivePriority: 3,
                },
                {
                    data: '3',
                    title: 'Direccion',
                },
                {
                    data: '4',
                    title: 'Estado',
                },
                {
                    data: '0',
                    title: 'Acciones',
                    searchable: false,
                    sortable: false,
                    width: '18%',
                    render: (data) => simpleBtns(data) + detailsBtns(data) + inactivoBtn(data) +
                        linkHistorial("{% url 'clinica:diagnostico-details' pk=0 %}".replace("0", data))
                }
            ];

            $table.DataTable(getDefaultDataTables(url, language_url, columns));
        }

        $(document).ready(function () {
            defaultConfig();
            loadDataTable()
        });
    </script>
{% endblock %}

clinica/templates/pascientes/update.html
{% url 'clinica:paciente-update'  pk=object.id as action_url %}
{% include "snippets/form-content.html" with action=action_url title='Actualizar Paciente' %}